version: 0.2

phases:
    install:
        runtime-versions:
            java: ${JAVA}
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
    post_build:
         commands:
            - echo Build completed on `date
